// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbjesaqjwilaawhatedo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiamVzYXFqd2lsYWF3aGF0ZWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTg3NzAsImV4cCI6MjA2NTU3NDc3MH0.v3cEAunvwLAFYniRCBmzJTrqZsB4UHQmEIKL7HnWsQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);